### ISSUE TITLE
Updating Name and Address make the activity stack wrong

### ISSUE THREAD

**Issue by CDavidSamuelsson** [AlexTelon/FlexiCharge-Android#194]
If a user is updating its name or address the user then gets sent back to the profile activity, but at that moment it adds another instance of the profile activity to the stack. Therefore if the user uses the back button the app still stays on the same activity since the "old" one still is in the stack

**Comment by foal20ym** [comment]
Please expand and follow the bug template that can be found in the documentation. Otherwise we will have to close this issue without further action.
