### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by knowitrickard** [AlexTelon/FlexiCharge-Android#6]
As a user I want to be able to login with my user account.

- [x] #41 
- [ ] #9 
- [ ] #8 
- [ ] #5 
- [ ] #55
- [x] #47
- [x] #46

![image](https://user-images.githubusercontent.com/57109651/133072154-0cad7c5d-da27-484b-9383-02f3e88a074e.png)

**Comment by runil** [comment]
![image](https://user-images.githubusercontent.com/57109651/133070785-47cfe7df-9407-47b6-8f01-4d0bd13c0da5.png)
